### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by ghost** [archlinux-downgrade/downgrade#164]
### Checklist

- [x] No duplicate issues/PRs
- [x] Are you running the latest `downgrade` release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

### Background

I like it more to use guis.

### Proposed feature

That downgrade has a gui.

**Comment by atreyasha** [comment]
Thanks @Toadfield for this feature request.

While I personally do not foresee the implementation of a full-fledged GUI for `downgrade`, I could imagine porting the package selection menu to something like [`ncurses`](https://invisible-island.net/ncurses/ncurses.faq.html).

If we do go with this idea, it will probably come much later in terms of priorities. Also it would require a significant code addition/modification since I believe the `ncurses` application would have to be coded in `C`.

@pbrisbin WDYT?

**Comment by pbrisbin** [comment]
I won't stand in the way of a motivated user that wanted to code up a GUI for this, as long as the current interface continues to work. And if that led to downgrade exposing more flexible ways to call into a "core" set of functionality, that'd be a positive IMO too.

Personally, I always pictured piping downgrade into something like `fzf` as the next iteration of interface:

```
downgrade search firefox | fzf | downgrade
```

However, that's still TUI not GUI (as is ncurses, for that matter).

**Comment by atreyasha** [comment]
Ah interesting, I don't know much about `fzf` (perhaps you had mentioned it before); but it looks fairly easy to use/develop. In that case, I would be interested to work on a prototype sooner than mentioned earlier. We can discuss more in a future PR.

**Comment by atreyasha** [comment]
> However, that's still TUI not GUI (as is ncurses, for that matter).

True, TUI would still not address the exact feature request of a GUI. I will make a new issue for a TUI and leave this as GUI-only.

>I won't stand in the way of a motivated user that wanted to code up a GUI for this, as long as the current interface continues to work.

Yes we can leave this open to any motivated user(s) to code up a GUI.

**Comment by pbrisbin** [comment]
Closing as we don't plan to implement. Patches welcome!
