### ISSUE TITLE
Downgrade somehow bricked my entire system

### ISSUE THREAD

**Issue by Theslees** [archlinux-downgrade/downgrade#201]
### Checklist

- [N] No duplicate issues/PRs
- [Y] Are you running the latest `downgrade` release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

### Environment

* System information:

System is unusable so I dont know how to execute that command
* Downgrade version:

downgrade version was 11.2 I believe
### Description
Trying to downgrade gcc and gcc-libs caused the entiee system to be unresponsive after it finished, and upon force shutting it down and rebooting it, plasma became unbootable and would just kick me back into my login manager when trying to login.

### Steps to Reproduce

1. Install downgrade via yay
3. run `downgrade gcc gcc-libs` and choose 11.2.0 for both
4. System becomes unresponsive and only way to showdown is by forcing it, causing your DE oe any session to be unbootable

### Expected behavior

gcc and gcc-libs to downgrade from 12.1.0 to 11.2.0
### Actual behavior
I don't even know, it just broke everything and I don't understand how 

### Command trace

I don't know how to access the system so I think I might have to make a ubuntu recovery stick and see what I can do, but I don't even know what the command did.

**Comment by Theslees** [comment]
Uninstalling downgrade and reverting the changes it did in tty fixed it, now it's back to normal
If there's a log I can post please let me know because there isnt any log downgrade produced that I know of.

**Comment by atreyasha** [comment]
> Uninstalling downgrade and reverting the changes it did in tty fixed it, now it's back to normal

Okay, could you now share your system information and downgrade version (see commands in the PR template)?

> If there's a log I can post please let me know

Downgrade does not have a dedicated log. But since the installation procedure is done via `pacman`, you could post a snippet of the relevant lines in `/var/log/pacman.log`.

> Expected behavior
gcc and gcc-libs to downgrade from 12.1.0 to 11.2.0

I tried downgrading both `gcc` and `gcc-libs` as documented in both a VM and my local machine. Unfortunately (or fortunately) I did not encounter any such issues of "bricking". But then again I don't use KDE Plasma, so maybe that plays a part.

> Actual behavior
> I don't even know, it just broke everything and I don't understand how

Going forward, there are two causes to consider:

1. Was there an error within the execution of `downgrade` which caused the issue (eg. was there a bug in `downgrade` itself which altered the system in an unexpected way)?
2. Or did `downgrade` execute successfully and exit 0, and the issue was caused because of some dependency-related error in the system itself (eg. KDE Plasma uses a library which implicitly depends on a particular version of `gcc-libs` and this was not documented as an explicit dependency in the `PKGBUILD of the relevant package(s))?

As a maintainer of `downgrade`, my main concern is to ensure that `downgrade` did what it was expected/told to do i.e. downgrade packages. Based on my experiments, I can verify that `downgrade` indeed downgraded `gcc` and `gcc-libs` successfully. So from that perspective, I don't see an issue here for `downgrade`.

That being said, I am not saying that your issue is not valid; I just think (based on the evidence here) that the issue is not related to `downgrade` and more relevant to another package which implicitly depends on one or more of the downgraded packages.

As a final note, I would err on the side of caution when using `downgrade` to downgrade low-level packages such as `gcc` and `gcc-libs`; precisely because of the reasons mentioned above on implicit dependencies. If you really need to perform this downgrade, maybe it could make sense to look into A.L.A snapshots:

https://wiki.archlinux.org/title/Arch_Linux_Archive#How_to_restore_all_packages_to_a_specific_date

@pbrisbin WDYT?
