### ISSUE TITLE
Add datetime stamp of packages into list

### ISSUE THREAD

**Issue by jpka-** [archlinux-downgrade/downgrade#226]
### Checklist

- [_Looks like Yes_] No duplicate issues/PRs
- [_Yes_] Are you running the latest `downgrade` release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

### Background

While downgrading 'wine' multiple times to find its specific regression, i notice it will be good to have not just versions listed, but also dates of issue.

### Proposed feature

Please add approximate dates of packages (timestamp of files?) into list. Thanks.

**Comment by pbrisbin** [comment]
Thanks for the request. I've got a version of this locally that I'd like to run by you:

1. Since there's no date information in the ALA response, this only works for packages in cache
2. I'm using `stat -c '%y'` which is last modification time
3. I'm truncating it to date only
4. I'm showing it as the last column in the selection

![](https://files.pbrisbin.com/screenshots/screenshot.1134698.png)

Is that all good?

**Comment by jpka-** [comment]
Yes, it looks very good.
